# Generated by Django 4.2.5 on 2023-09-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('release', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='series')),
                ('link', models.URLField(unique=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='series_actor', to='actors.actor')),
                ('genders', models.ManyToManyField(blank=True, related_name='series', to='genders.gender')),
                ('languages', models.ManyToManyField(blank=True, related_name='series', to='languages.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_series', to='series.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorites Series',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_series', to='series.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'unique_together': {('serie', 'user')},
            },
        ),
    ]
